version: "3.8"

services:
  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
    - ./data/:/var/lib/grafana
    - ./config/grafana.ini:/etc/grafana/grafana.ini
    - ./custom-files/:/usr/share/grafana/public/views/

networks:
  default:
    external:
      name: rubikx-iot-nw
