version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
    - ./data/:/var/lib/grafana
    - ./config/grafana.ini:/etc/grafana/grafana.ini

networks:
  default:
    external:
      name: rubikx-iot-nw
